/**
 * AI Agent Types - Core Type Definitions
 * 
 * TypeScript interfaces for the AI agent orchestration system.
 * Supports natural language interaction, profile extraction, and recommendations.
 * 
 * @module agents/ai/types
 */

import { ScenarioId } from '../../config/scenarioTypes'
import { ScenarioArchetype } from '../../config/archetypes'
import type { ScenarioModifier } from '../../config/archetypeContracts'
import { UserProfile, Recommendation } from '../types'

// ============================================================================
// CONVERSATION TYPES
// ============================================================================

/**
 * Chat message in a conversation
 */
export interface Message {
  /** Message role */
  role: 'user' | 'assistant' | 'system'

  /** Message content */
  content: string

  /** Timestamp of message */
  timestamp: Date

  /** Optional metadata */
  metadata?: Record<string, any>
}

/**
 * Conversation context for maintaining state
 */
export interface ConversationContext {
  /** List of messages in conversation */
  messages: Message[]

  /** Extracted user profile (partial during conversation) */
  extractedProfile?: Partial<UserProfile>

  /** Identified financial goals */
  identifiedGoals?: GoalIntent[]

  /** Session ID for tracking */
  sessionId: string

  /** User ID (optional, can be anonymized) */
  userId?: string

  /** Conversation started timestamp */
  startedAt: Date

  /** Last updated timestamp */
  updatedAt: Date
}

// ============================================================================
// GOAL UNDERSTANDING TYPES
// ============================================================================

/**
 * User's financial goal identified from conversation
 */
export interface GoalIntent {
  /** Intent type (e.g., "save_for_house", "reduce_debt") */
  intentType: string

  /** Confidence in this interpretation (0-1) */
  confidence: number

  /** Extracted details from user input */
  extractedDetails: Record<string, any>

  /** Related scenario IDs that could fulfill this goal */
  potentialScenarios: ScenarioId[]

  /** Free-form description of the goal */
  description: string
}

// ============================================================================
// AGENT RESPONSE TYPES
// ============================================================================

/**
 * Response from AI agent to user
 */
export interface AgentResponse {
  /** Message to display to user */
  message: string

  /** Scenario recommendations (if any) */
  recommendations?: Recommendation[]

  /** Follow-up questions to ask user */
  questionsForUser?: string[]

  /** Partially extracted profile data */
  profileExtracted?: Partial<UserProfile>

  /** Profile fields that are still missing */
  missingProfileFields?: string[]

  /** Overall confidence in the response (0-1) */
  confidence: number

  /** Agent's reasoning (for debugging/transparency) */
  reasoning?: string

  /** Whether profile extraction is complete */
  profileComplete?: boolean
}

// ============================================================================
// CUSTOM SCENARIO TYPES
// ============================================================================

/**
 * Custom scenario generated by AI for unique user needs
 */
export interface CustomScenario {
  /** Human-readable description of the custom scenario */
  description: string

  /** Display name for the scenario */
  displayName: string

  /** Scenario modifiers to apply */
  modifiers: ScenarioModifier[]

  /** Explanation of why this custom scenario was created */
  reasoning: string

  /** Archetypes used in this custom scenario */
  archetypesUsed: ScenarioArchetype[]

  /** UK tax considerations for this scenario */
  ukTaxConsiderations: string[]

  /** Confidence that this meets user's needs (0-1) */
  confidence: number

  /** Whether this requires FCA review */
  requiresFCAReview: boolean
}

// ============================================================================
// LLM CLIENT TYPES
// ============================================================================

/**
 * LLM provider configuration
 */
export interface LLMConfig {
  /** API key for the LLM provider */
  apiKey: string

  /** Model to use (e.g., "gpt-4o-mini", "gpt-4o") */
  model: string

  /** Temperature for responses (0-2, lower = more deterministic) */
  temperature?: number

  /** Maximum tokens in response */
  maxTokens?: number

  /** Enable JSON mode for structured output */
  jsonMode?: boolean
}

/**
 * LLM API response
 */
export interface LLMResponse<T = any> {
  /** Parsed response content */
  content: T

  /** Raw response text */
  rawText: string

  /** Tokens used in prompt */
  promptTokens: number

  /** Tokens used in completion */
  completionTokens: number

  /** Total tokens used */
  totalTokens: number

  /** Model used for generation */
  model: string

  /** Finish reason (e.g., "stop", "length") */
  finishReason: string | null
}

/**
 * Structured prompt for LLM with schema validation
 */
export interface StructuredPrompt<T> {
  /** System instruction */
  systemPrompt: string

  /** User message */
  userPrompt: string

  /** Example conversations (few-shot learning) */
  examples?: Array<{ user: string; assistant: string }>

  /** JSON schema for expected response structure */
  responseSchema?: any  // Zod schema or JSON Schema

  /** Parser function for response */
  parser?: (rawResponse: string) => T
}

// ============================================================================
// PROFILE EXTRACTION TYPES
// ============================================================================

/**
 * Result of profile extraction from conversation
 */
export interface ProfileExtractionResult {
  /** Extracted profile data */
  profile: Partial<UserProfile>

  /** Fields successfully extracted */
  extractedFields: string[]

  /** Fields still missing */
  missingFields: string[]

  /** Confidence in extraction (0-1) */
  confidence: number

  /** Questions to ask to fill missing fields */
  suggestedQuestions: string[]

  /** Whether profile is complete enough for recommendations */
  isComplete: boolean
}

// ============================================================================
// RECOMMENDATION TYPES (extending base types)
// ============================================================================

/**
 * AI-generated recommendation with enhanced context
 */
export interface AIRecommendation extends Recommendation {
  /** Whether this came from rules engine or AI */
  source: 'rules' | 'ai' | 'hybrid'

  /** AI's natural language explanation */
  aiExplanation?: string

  /** Comparison to alternative scenarios */
  alternatives?: Array<{
    scenarioId: ScenarioId
    pros: string[]
    cons: string[]
  }>

  /** Risk assessment */
  riskLevel?: 'low' | 'medium' | 'high'

  /** UK-specific considerations */
  ukConsiderations?: string[]
}

// ============================================================================
// ERROR TYPES
// ============================================================================

/**
 * AI agent error
 */
export class AIAgentError extends Error {
  constructor(
    message: string,
    public code: string,
    public details?: any
  ) {
    super(message)
    this.name = 'AIAgentError'
  }
}

/**
 * LLM API error
 */
export class LLMAPIError extends AIAgentError {
  constructor(
    message: string,
    public statusCode?: number,
    details?: any
  ) {
    super(message, 'LLM_API_ERROR', details)
    this.name = 'LLMAPIError'
  }
}

/**
 * Profile extraction error
 */
export class ProfileExtractionError extends AIAgentError {
  constructor(message: string, details?: any) {
    super(message, 'PROFILE_EXTRACTION_ERROR', details)
    this.name = 'ProfileExtractionError'
  }
}
