/**
 * AI Recommendations Component
 * 
 * Displays scenario recommendations generated by the rules engine
 * with full visibility into reasoning and calculation traces.
 */

import { useState, useEffect } from 'react'
import { useScenarioStore } from '../state/scenarioStore'
import { evaluateRules, getEnabledRules, type RulesEvaluationResult, type Recommendation, type RuleContext } from '@financial-sandbox/sim-core'
import '../styles/AIRecommendations.css'

export function AIRecommendations() {
    const { state, dispatch } = useScenarioStore()
    const [recommendations, setRecommendations] = useState<Recommendation[]>([])
    const [evaluationResult, setEvaluationResult] = useState<RulesEvaluationResult | null>(null)
    const [expandedRec, setExpandedRec] = useState<string | null>(null)
    const [isEvaluating, setIsEvaluating] = useState(false)

    const handleEvaluate = () => {
        setIsEvaluating(true)

        // Build user profile from current state
        const profile = {
            age: state.currentAge,
            retirementAge: state.retirementAge,
            currentSalary: state.selectedProfile.currentSalary,
            monthlyExpenses: state.selectedProfile.monthlyExpenses,
            pensionBalance: state.selectedProfile.pensionBalance,

            // Extract from profile data (with defaults)
            savingsBalance: state.selectedProfile.savingsBalance || 0,
            isaBalance: state.selectedProfile.isaBalance || 0,
            mortgageBalance: state.selectedProfile.mortgageBalance || 0,
            mortgageRate: state.selectedProfile.mortgageRate || 0,
            otherDebtBalance: state.selectedProfile.otherDebtBalance || 0,

            // Flags
            hasEmergencyFund: state.selectedProfile.hasEmergencyFund || false,
            hasChildren: state.selectedProfile.hasChildren || 0,
            riskTolerance: state.selectedProfile.riskTolerance || 'medium' as 'low' | 'medium' | 'high'
        }

        // Build context
        const context: RuleContext = {
            profile,
            enabledScenarios: Object.values(state.scenarios)
                .filter(s => s.enabled)
                .map(s => s.id as any),  // Type cast for compatibility
            currentDate: new Date(),
            sessionId: `session-${Date.now()}`
        }

        // Evaluate rules
        const rules = getEnabledRules()
        const result = evaluateRules(rules, context)

        setEvaluationResult(result)
        setRecommendations(result.recommendations)
        setIsEvaluating(false)
    }

    const handleApplyRecommendation = (rec: Recommendation) => {
        // Apply the recommendation by enabling the scenario with suggested params
        dispatch({
            type: 'ADD_SCENARIO',
            scenario: {
                id: rec.scenarioId,
                type: 'action', // Default, will be overridden by actual type
                enabled: true,
                data: rec.suggestedParams,
                _simplifiedInputs: rec.suggestedParams
            }
        })

        // Remove from recommendations
        setRecommendations(prev => prev.filter(r => r.scenarioId !== rec.scenarioId))
    }

    const handleDismissRecommendation = (rec: Recommendation) => {
        setRecommendations(prev => prev.filter(r => r.scenarioId !== rec.scenarioId))
    }

    const toggleExpanded = (scenarioId: string) => {
        setExpandedRec(expandedRec === scenarioId ? null : scenarioId)
    }

    // Auto-evaluate on mount and when profile changes
    useEffect(() => {
        handleEvaluate()
    }, [state.selectedProfile.id, state.currentAge, state.retirementAge])

    return (
        <div className="ai-recommendations">
            <div className="ai-header">
                <h3>🤖 AI Recommendations</h3>
                <button
                    onClick={handleEvaluate}
                    disabled={isEvaluating}
                    className="evaluate-btn"
                >
                    {isEvaluating ? 'Analyzing...' : 'Refresh Suggestions'}
                </button>
            </div>

            {evaluationResult && (
                <div className="evaluation-stats">
                    <span>Evaluated {evaluationResult.totalRulesEvaluated} rules</span>
                    <span>•</span>
                    <span>{evaluationResult.totalRulesMatched} matched</span>
                    <span>•</span>
                    <span>{recommendations.length} recommendations</span>
                </div>
            )}

            {recommendations.length === 0 ? (
                <div className="no-recommendations">
                    <p>✨ No new recommendations at this time.</p>
                    <p className="subtext">
                        Your current profile looks well-optimized! Check back after making changes.
                    </p>
                </div>
            ) : (
                <div className="recommendations-list">
                    {recommendations.map((rec) => (
                        <div key={rec.scenarioId} className="recommendation-card">
                            <div className="rec-header">
                                <div className="rec-title-section">
                                    <h4>{rec.scenarioId.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase())}</h4>
                                    <div className="rec-meta">
                                        <span className="confidence-badge" style={{
                                            background: rec.confidence >= 0.8 ? '#10b981' : rec.confidence >= 0.6 ? '#f59e0b' : '#94a3b8'
                                        }}>
                                            {Math.round(rec.confidence * 100)}% confidence
                                        </span>
                                        <span className="priority-badge">
                                            Priority: {rec.priority}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <p className="rec-reasoning">{rec.reasoning}</p>

                            {rec.tags && rec.tags.length > 0 && (
                                <div className="rec-tags">
                                    {rec.tags.map((tag: string) => (
                                        <span key={tag} className="tag">{tag}</span>
                                    ))}
                                </div>
                            )}

                            <div className="rec-params">
                                <strong>Suggested Configuration:</strong>
                                <ul>
                                    {Object.entries(rec.suggestedParams).map(([key, value]) => (
                                        <li key={key}>
                                            <strong>{key}:</strong> {formatValue(value)}
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            <button
                                className="show-reasoning-btn"
                                onClick={() => toggleExpanded(rec.scenarioId)}
                            >
                                {expandedRec === rec.scenarioId ? '▼' : '▶'} Show Calculation Details
                            </button>

                            {expandedRec === rec.scenarioId && (
                                <div className="calculation-trace">
                                    <h5>📊 Calculation Steps:</h5>
                                    {rec.calculationTrace.map((step: any) => (
                                        <div key={step.step} className="calc-step">
                                            <div className="step-number">Step {step.step}</div>
                                            <div className="step-content">
                                                <p className="step-description">{step.description}</p>
                                                {step.formula && (
                                                    <code className="step-formula">{step.formula}</code>
                                                )}
                                                {step.inputs && Object.keys(step.inputs).length > 0 && (
                                                    <div className="step-inputs">
                                                        <strong>Inputs:</strong>
                                                        {Object.entries(step.inputs).map(([k, v]) => (
                                                            <span key={k}> {k}={formatValue(v)}</span>
                                                        ))}
                                                    </div>
                                                )}
                                                <div className="step-result">
                                                    <strong>Result:</strong> {formatValue(step.result)} {step.units || ''}
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}

                            <div className="rec-actions">
                                <button
                                    className="apply-btn"
                                    onClick={() => handleApplyRecommendation(rec)}
                                >
                                    ✓ Apply Recommendation
                                </button>
                                <button
                                    className="dismiss-btn"
                                    onClick={() => handleDismissRecommendation(rec)}
                                >
                                    ✕ Dismiss
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    )
}

function formatValue(value: any): string {
    if (typeof value === 'number') {
        // Check if it looks like currency
        if (value >= 100 || value % 1 !== 0) {
            return `£${value.toLocaleString()}`
        }
        return value.toString()
    }

    if (value instanceof Date) {
        return value.toLocaleDateString('en-GB')
    }

    if (typeof value === 'string') {
        // Check if it's a date string (YYYY-MM-DD format)
        if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
            return new Date(value).toLocaleDateString('en-GB')
        }
    }

    return String(value)
}
